//
// Generated file, do not edit! Created by opp_msgtool 6.0 from Message.msg.
//

#ifndef __MESSAGE_M_H
#define __MESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Package;
/**
 * Class generated from <tt>Message.msg:19</tt> by opp_msgtool.
 * <pre>
 * packet Package
 * {
 *     int srcAddr \@packetData;
 *     int destAddr \@packetData;
 *     // long seq;
 * }
 * </pre>
 */
class Package : public ::omnetpp::cPacket
{
  protected:
    int srcAddr = 0;
    int destAddr = 0;

  private:
    void copy(const Package& other);

  protected:
    bool operator==(const Package&) = delete;

  public:
    Package(const char *name=nullptr, short kind=0);
    Package(const Package& other);
    virtual ~Package();
    Package& operator=(const Package& other);
    virtual Package *dup() const override {return new Package(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSrcAddr() const;
    virtual void setSrcAddr(int srcAddr);

    virtual int getDestAddr() const;
    virtual void setDestAddr(int destAddr);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Package& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Package& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline Package *fromAnyPtr(any_ptr ptr) { return check_and_cast<Package*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MESSAGE_M_H

